### ISSUE TITLE
화상강의 참여하기 버튼이 작성자가 아닌 사람에게도 보입니다.

### ISSUE THREAD

**Issue by dezyon1** [MY-Park/my-first-blog#13]
화상강의 참여하기 버튼이 모든 사용자에게 보입니다. 갑자기 다른 사용자가 강의에 난입할수있을거같습니다.
수정해야합니다.

**Comment by hayoyo12** [comment]
화상강의 참여하기 버튼 작성자에게만 시간에 맞춰 보이게 수정 완료 했습니다.
