### ISSUE TITLE
다른 사용자가 작성한 게시물에 '좋아요' 기능 추가

### ISSUE THREAD

**Issue by dezyon1** [MY-Park/my-first-blog#7]
다른 사용자가 작성한 게시물에 '좋아요' 기능 추가

**Comment by hayoyo12** [comment]
다른 사용자가 작성한 게시물에 '좋아요' 기능 추가 완료 및 중복 확인
![image](https://user-images.githubusercontent.com/56079352/86322059-36836e00-bc75-11ea-8c3b-1b3f56f0e300.png)
