### ISSUE TITLE
댓글 작성시 사용자 이름 입력해야 하는 문제 발견

### ISSUE THREAD

**Issue by dezyon1** [MY-Park/my-first-blog#9]
댓글 작성시 사용자 이름 입력해야 하는 문제 발견

**Comment by hayoyo12** [comment]
댓글 작성시 내용만 작성 가능하게 수정 완료
![image](https://user-images.githubusercontent.com/56079352/86322097-4b600180-bc75-11ea-9e30-e84b7d084a3c.png)
